# Generated by Django 6.0.3 on 2026-05-13 03:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Caso creado"),
                    ("UPDATED", "Caso actualizado"),
                    ("STATUS_CHANGED", "Estado cambiado"),
                    ("ASSIGNED", "Estudiante asignado"),
                    ("REASSIGNED", "Caso reasignado"),
                    ("FILE_UPLOADED", "Archivo adjuntado"),
                    ("FILE_DELETED", "Archivo eliminado"),
                    ("REJECTED", "Caso rechazado"),
                    ("CLOSED", "Caso cerrado"),
                    ("VIEWED", "Caso consultado"),
                    ("COMMUNICATION", "Interacción de comunicación"),
                ],
                max_length=20,
                verbose_name="Acción",
            ),
        ),
        migrations.CreateModel(
            name="CommunicationInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("mensaje", "Mensaje"),
                            ("llamada", "Llamada"),
                            ("correo", "Correo electrónico"),
                            ("presencial", "Presencial"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de interacción",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("entrante", "Entrante"), ("saliente", "Saliente")],
                        max_length=10,
                        verbose_name="Dirección",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="cases.case",
                        verbose_name="Caso",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interacción de comunicación",
                "verbose_name_plural": "Interacciones de comunicación",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["case", "-timestamp"],
                        name="cases_commu_case_id_186bf1_idx",
                    )
                ],
            },
        ),
    ]
