# Generated by Django 6.0.3 on 2026-05-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_security_denied_action'),
        ('cases', '0002_alter_caseauditlog_action_communicationinteraction'),
    ]

    operations = [
    ]
