# Generated by Django 6.0.3 on 2026-05-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_merge_20260523_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseauditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Bitacora de Caso', 'verbose_name_plural': 'Bitacora de Casos'},
        ),
        migrations.AlterModelOptions(
            name='communicationinteraction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Interaccion de comunicacion', 'verbose_name_plural': 'Interacciones de comunicacion'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterField(
            model_name='caseauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Caso creado'), ('UPDATED', 'Caso actualizado'), ('STATUS_CHANGED', 'Estado cambiado'), ('ASSIGNED', 'Estudiante asignado'), ('REASSIGNED', 'Caso reasignado'), ('FILE_UPLOADED', 'Archivo adjuntado'), ('FILE_DELETED', 'Archivo eliminado'), ('REJECTED', 'Caso rechazado'), ('CLOSED', 'Caso cerrado'), ('VIEWED', 'Caso consultado'), ('SECURITY_DENIED', 'Acceso denegado'), ('COMMUNICATION', 'Interacción de comunicación')], max_length=20, verbose_name='Accion'),
        ),
        migrations.AlterField(
            model_name='caseauditlog',
            name='description',
            field=models.TextField(verbose_name='Descripcion de la accion'),
        ),
        migrations.AlterField(
            model_name='caseauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP'),
        ),
        migrations.AlterField(
            model_name='communicationinteraction',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='communicationinteraction',
            name='direction',
            field=models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=10, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='communicationinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('mensaje', 'Mensaje'), ('llamada', 'Llamada'), ('correo', 'Correo electronico'), ('presencial', 'Presencial')], max_length=20, verbose_name='Tipo de interaccion'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leida'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Cambio de estado'), ('ASSIGNMENT', 'Asignacion de estudiante'), ('DEADLINE', 'Alerta de vencimiento'), ('GENERAL', 'Informacion general')], default='STATUS_CHANGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Leida el'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
