# Generated by Django 6.0.3 on 2026-05-23 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_add_audio_file_to_communicationinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('offer_sdp', models.TextField(blank=True, null=True)),
                ('answer_sdp', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Esperando'), ('active', 'Activa'), ('ended', 'Finalizada')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesion de llamada',
                'verbose_name_plural': 'Sesiones de llamada',
            },
        ),
    ]
