# Generated by Django 6.0.3 on 2026-05-23 05:33

import cases.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_add_callsession_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationinteraction',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=cases.models.call_recording_upload_path, verbose_name='Grabacion de llamada'),
        ),
    ]
