# Generated by Django 6.0.3 on 2026-05-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_alter_caseauditlog_options_and_more"),
        ("cases", "0005_caseevaluation_score_decimal"),
    ]

    operations = []
