# Generated by Django 6.0.3 on 2026-05-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_merge_20260524_1133'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caseevaluation',
            new_name='cases_casee_student_8f136d_idx',
            old_name='cases_casee_student_6a0f58_idx',
        ),
        migrations.RenameIndex(
            model_name='caseevaluation',
            new_name='cases_casee_case_id_1279ad_idx',
            old_name='cases_casee_case_f0b41e_idx',
        ),
    ]
