# Generated by Django 6.0.3 on 2026-05-24 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_caseevaluation_score_decimal'),
        ('cases', '0006_audio_file_raw_storage'),
    ]

    operations = [
    ]
