# Generated by Django 6.0.3 on 2026-05-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_merge_20260523_2304"),
        (
            "cases",
            "0007_rename_cases_casee_student_6a0f58_idx_cases_casee_student_8f136d_idx_and_more",
        ),
    ]

    operations = []
