# Generated by Django 6.0.3 on 2026-05-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_audio_file_raw_storage"),
        ("cases", "0008_merge_20260524_1418"),
    ]

    operations = []
