# Generated by Django 6.0.3 on 2026-05-25 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiary", "0006_encrypt_sensitive_fields"),
        ("cases", "0009_merge_20260524_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="beneficiary",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="beneficiary.beneficiary",
                verbose_name="Beneficiario",
            ),
            preserve_default=False,
        ),
    ]
