# Generated by Django 6.0.3 on 2026-05-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_merge_20260524_1543'),
        ('cases', '0009_merge_20260524_1703'),
    ]

    operations = [
    ]
