# Generated by Django 6.0.3 on 2026-05-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_merge_20260523_1915'),
        ('cases', '0012_case_beneficiary_nullable_for_drafts'),
    ]

    operations = [
    ]
