# Generated by Django 6.0.3 on 2026-04-25 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, verbose_name='Número de Identificación')),
                ('location', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('date_register', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'ordering': ['-date_register'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Beneficiario registrado'), ('VIEWED', 'Datos consultados'), ('UPDATED', 'Datos actualizados'), ('DELETED', 'Beneficiario eliminado'), ('DOC_UPLOADED', 'Documento cargado'), ('DOC_DELETED', 'Documento eliminado'), ('DEACTIVATED', 'Beneficiario desactivado'), ('REACTIVATED', 'Beneficiario reactivado'), ('DATA_EXPORT', 'Datos exportados'), ('DELETE_REQUEST', 'Solicitud de eliminación registrada')], max_length=20, verbose_name='Acción')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('changed_fields', models.JSONField(blank=True, help_text='Diccionario: { "Campo": { "anterior": "...", "nuevo": "..." } }', null=True, verbose_name='Campos modificados')),
                ('beneficiary_document', models.CharField(blank=True, max_length=30, verbose_name='Documento')),
                ('beneficiary_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='beneficiary.beneficiary', verbose_name='Beneficiario')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la acción')),
            ],
            options={
                'verbose_name': 'Bitácora de Beneficiario',
                'verbose_name_plural': 'Bitácora de Beneficiarios',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['beneficiary', '-timestamp'], name='beneficiary_benefic_31f428_idx'), models.Index(fields=['user', '-timestamp'], name='beneficiary_user_id_d2804d_idx'), models.Index(fields=['action'], name='beneficiary_action_bde564_idx')],
            },
        ),
    ]
