# Generated by Django 6.0.3 on 2026-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='colombian_identification',
            field=models.CharField(default='', max_length=20, verbose_name='Cédula de Ciudadanía'),
        ),
    ]
