# Generated by Django 6.0.3 on 2026-04-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_beneficiaryauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Número de Identificación'),
        ),
    ]
