# Generated by Django 6.0.3 on 2026-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_documentbeneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Beneficiario registrado'), ('VIEWED', 'Datos consultados'), ('UPDATED', 'Datos actualizados'), ('DELETED', 'Beneficiario eliminado'), ('DOC_UPLOADED', 'Documento cargado'), ('DOC_DELETED', 'Documento eliminado'), ('DEACTIVATED', 'Beneficiario desactivado'), ('REACTIVATED', 'Beneficiario reactivado'), ('DATA_EXPORT', 'Datos exportados'), ('DELETE_REQUEST', 'Solicitud de eliminación registrada'), ('CITE_ATTENDED', 'Asistencia registrada'), ('CITE_MISSED', 'Inasistencia registrada')], max_length=20, verbose_name='Acción'),
        ),
    ]
