# Generated by Django 6.0.3 on 2026-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_alter_beneficiary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='id',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, verbose_name='Número de Identificación'),
        ),
    ]
