# Generated by Django 6.0.3 on 2026-04-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiary', '0002_beneficiary_colombian_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de cita')),
                ('date_assigned', models.DateField()),
                ('modality_cite', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELEFONICA', 'Telefonica'), ('VIRTUAL', 'Virtual')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad')),
                ('state_cite', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Atendida', 'Atendida')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('request_cite', models.CharField(choices=[('Presencial', 'Presencial'), ('Telefonica', 'Telefonica'), ('Página Web', 'Pagina Web'), ('Correo Electronico', 'Correo Electronico')], default='Página Web', max_length=20, verbose_name='Medio de Solicitud')),
                ('description', models.CharField(max_length=2000, verbose_name='Descripcion')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cites', to='beneficiary.beneficiary', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-id'],
            },
        ),
    ]
