# Generated by Django 6.0.3 on 2026-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0004_merge_20260504_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cite',
            name='date_assigned',
            field=models.DateTimeField(),
        ),
    ]
