"""
Django settings for Gestion_Casos_Django_T4 project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-hof5w4+lwcyquh4n-xyfc(q0bskiz&q%(4beypw197+^(1*)!2')
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

_hosts = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = _hosts.split(',') if _hosts else ['localhost', '127.0.0.1']

_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if _origins:
    CSRF_TRUSTED_ORIGINS = _origins.split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'accounts',
    'beneficiary',
    'cases',
    'cite',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Gestion_Casos_Django_T4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_roles',
                'cases.context_processors.notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gestion_Casos_Django_T4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ── Internacionalización ─────────────────────────────────
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True

USE_TZ = True

# ── Archivos estáticos y media ───────────────────────────
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]   # Carpeta global de estáticos
STATIC_ROOT = BASE_DIR / "staticfiles"     # Para collectstatic en producción

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Auth redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'beneficiary_list'
LOGOUT_REDIRECT_URL = 'login'

# ── Correo electrónico — HU-13 ──────────────────────────────────────────
# Desarrollo: imprime el correo en la consola del runserver (no necesita SMTP)
EMAIL_BACKEND      = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Consultorio Jurídico ICESI <consultorio@icesi.edu.co>'

# Para producción, comentar el backend de consola y descomentar esto:
# EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST          = 'smtp.gmail.com'
# EMAIL_PORT          = 587
# EMAIL_USE_TLS       = True
# EMAIL_HOST_USER     = 'tu_correo@icesi.edu.co'
# EMAIL_HOST_PASSWORD = 'tu_contraseña_de_aplicacion'

# ── Configuración por defecto ────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
