# Generated by Django 6.0.3 on 2026-04-25 18:51

import cases.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Codigo')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('completo', 'Completo')], default='completo', max_length=20, verbose_name='Estado del formulario')),
                ('sala', models.CharField(blank=True, choices=[('civil', 'Civil'), ('laboral', 'Laboral'), ('penal', 'Penal'), ('publico', 'Publico'), ('familia', 'Familia')], max_length=20, null=True, verbose_name='Sala juridica')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion del problema')),
                ('state', models.CharField(default='Registrado - Pendiente asignacion', max_length=100, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Fecha limite de atencion')),
                ('deadline_alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Alerta de vencimiento enviada el')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Causal de rechazo')),
                ('assigned_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante asignado')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='beneficiary.beneficiary', verbose_name='Beneficiario')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cases.models.case_document_upload_path, verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Documento del caso',
                'verbose_name_plural': 'Documentos del caso',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseReassignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_logs', to='cases.case', verbose_name='Caso')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_reassignment_logs', to=settings.AUTH_USER_MODEL, verbose_name='Reasignado por')),
                ('new_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante nuevo')),
                ('old_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante anterior')),
            ],
            options={
                'verbose_name': 'Bitacora de reasignacion',
                'verbose_name_plural': 'Bitacora de reasignaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Caso creado'), ('UPDATED', 'Caso actualizado'), ('STATUS_CHANGED', 'Estado cambiado'), ('ASSIGNED', 'Estudiante asignado'), ('REASSIGNED', 'Caso reasignado'), ('FILE_UPLOADED', 'Archivo adjuntado'), ('FILE_DELETED', 'Archivo eliminado'), ('REJECTED', 'Caso rechazado'), ('CLOSED', 'Caso cerrado'), ('VIEWED', 'Caso consultado')], max_length=20, verbose_name='Acción')),
                ('description', models.TextField(verbose_name='Descripción de la acción')),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado nuevo')),
                ('case_radicado', models.CharField(blank=True, max_length=50, verbose_name='Radicado del caso')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cases.case', verbose_name='Caso')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Bitácora de Caso',
                'verbose_name_plural': 'Bitácora de Casos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['case', '-timestamp'], name='cases_casea_case_id_b21192_idx'), models.Index(fields=['user', '-timestamp'], name='cases_casea_user_id_6843f7_idx'), models.Index(fields=['action'], name='cases_casea_action_f6c8ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('STATUS_CHANGE', 'Cambio de estado'), ('ASSIGNMENT', 'Asignación de estudiante'), ('DEADLINE', 'Alerta de vencimiento'), ('GENERAL', 'Información general')], default='STATUS_CHANGE', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada el')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case', verbose_name='Caso relacionado')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user', 'is_read'], name='cases_notif_recipie_c68dcd_idx'), models.Index(fields=['case'], name='cases_notif_case_id_f14bf9_idx')],
            },
        ),
    ]
