# Generated by Django 6.0.4 on 2026-04-11 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_create_default_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Caso creado"),
                            ("UPDATED", "Caso actualizado"),
                            ("STATUS_CHANGED", "Estado cambiado"),
                            ("ASSIGNED", "Estudiante asignado"),
                            ("REASSIGNED", "Caso reasignado"),
                            ("FILE_UPLOADED", "Archivo adjuntado"),
                            ("FILE_DELETED", "Archivo eliminado"),
                            ("REJECTED", "Caso rechazado"),
                            ("CLOSED", "Caso cerrado"),
                            ("VIEWED", "Caso consultado"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descripción de la acción"),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Estado anterior",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Estado nuevo",
                    ),
                ),
                (
                    "case_radicado",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Radicado del caso"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="cases.case",
                        verbose_name="Caso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora de Caso",
                "verbose_name_plural": "Bitácora de Casos",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["case", "-timestamp"],
                        name="cases_casea_case_id_b21192_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="cases_casea_user_id_6843f7_idx",
                    ),
                    models.Index(
                        fields=["action"], name="cases_casea_action_f6c8ef_idx"
                    ),
                ],
            },
        ),
    ]
