# Generated by Django 6.0.4 on 2026-04-11 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_add_administrador_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("STATUS_CHANGE", "Cambio de estado"),
                            ("ASSIGNMENT", "Asignación de estudiante"),
                            ("DEADLINE", "Alerta de vencimiento"),
                            ("GENERAL", "Información general"),
                        ],
                        default="STATUS_CHANGE",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "previous_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("new_status", models.CharField(blank=True, max_length=50, null=True)),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creada el"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Leída el"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="cases.case",
                        verbose_name="Caso relacionado",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_user", "is_read"],
                        name="cases_notif_recipie_c68dcd_idx",
                    ),
                    models.Index(
                        fields=["case"], name="cases_notif_case_id_f14bf9_idx"
                    ),
                ],
            },
        ),
    ]
