# Generated by Django 6.0.3 on 2026-04-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_caseauditlog'),
        ('cases', '0005_casereassignmentlog'),
        ('cases', '0005_notification'),
    ]

    operations = [
    ]
