# Generated by Django 6.0.3 on 2026-04-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casereassignmentlog'),
        ('cases', '0006_merge_0004_caseauditlog_0005_notification'),
    ]

    operations = [
    ]
