# Generated by Django 6.0.3 on 2026-04-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_merge_20260411_2250'),
        ('cases', '0007_merge_all_branches'),
    ]

    operations = [
    ]
