# Generated by Django 6.0.3 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_merge_20260412_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha limite de atencion'),
        ),
        migrations.AddField(
            model_name='case',
            name='deadline_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Alerta de vencimiento enviada el'),
        ),
    ]
