# Generated by Django 6.0.3 on 2026-04-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Causal de rechazo'),
        ),
    ]
