# Generated by Django 6.0.3 on 2026-04-23 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_alter_beneficiary_id'),
        ('cases', '0010_case_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('completo', 'Completo')], default='completo', max_length=20, verbose_name='Estado del formulario'),
        ),
        migrations.AlterField(
            model_name='case',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='beneficiary.beneficiary', verbose_name='Beneficiario'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion del problema'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sala',
            field=models.CharField(blank=True, choices=[('civil', 'Civil'), ('laboral', 'Laboral'), ('penal', 'Penal'), ('publico', 'Publico'), ('familia', 'Familia')], max_length=20, null=True, verbose_name='Sala juridica'),
        ),
    ]
