# Generated by Django 6.0.3 on 2026-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cite',
            name='state_cite',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Atendida', 'Atendida'), ('Asistió', 'Asistió'), ('No asistió', 'No asistió')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
