# Generated by Django 6.0.3 on 2026-05-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Recordatorio enviado'),
        ),
    ]
