# Generated by Django 6.0.3 on 2026-05-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cite", "0003_merge_0002_branches"),
        ("cite", "0003_merge_20260503_1110"),
    ]

    operations = []
