# Generated by Django 6.0.3 on 2026-04-26 20:38

import beneficiary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_beneficiary_colombian_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=beneficiary.models.beneficiary_document_path, verbose_name='Archivo')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='beneficiary.beneficiary', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Documento de Identidad del Beneficiario',
                'verbose_name_plural': 'Documentos de Identidad del Beneficiario',
                'ordering': ['-date_upload'],
            },
        ),
    ]
