# Generated by Django 6.0.3 on 2026-05-17 22:21

import beneficiary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiary", "0005_datadeletionrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="colombian_identification",
            field=beneficiary.models.EncryptedCharField(
                default="", max_length=512, verbose_name="Cédula de Ciudadanía"
            ),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="phone",
            field=beneficiary.models.EncryptedCharField(
                max_length=512, verbose_name="Teléfono"
            ),
        ),
    ]
