from django.urls import path

from . import views

urlpatterns = [
    path('', views.case_list, name='case_list'),
    path('panel-academico/', views.academic_dashboard, name='academic_dashboard'),
    path('panel-academico/estudiante/<int:student_id>/', views.academic_student_detail, name='case_academic_student_detail'),
    path('panel-academico/exportar/excel/', views.export_academic_dashboard_excel, name='academic_dashboard_export_excel'),
    path('panel-academico/exportar/pdf/', views.export_academic_dashboard_pdf, name='academic_dashboard_export_pdf'),
    path('registrar/', views.case_create, name='case_create'),
    path('borradores/', views.case_draft_list, name='case_draft_list'),
    path('borradores/<int:pk>/editar/', views.case_edit_draft, name='case_edit_draft'),
    path('<int:pk>/', views.case_detail, name='case_detail'),
    path('<int:pk>/fecha-limite/', views.case_update_deadline, name='case_update_deadline'),
    path('notificaciones/',                            views.notification_list,           name='notification_list'),
    path('notificaciones/<int:notification_id>/leer/', views.mark_notification_read,      name='mark_notification_read'),
    path('notificaciones/leer-todas/',                 views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notificaciones/contador/',                   views.unread_notifications_count,  name='unread_count'),
    path('<int:case_id>/bitacora/', views.case_audit_log, name='case_audit_log'),
    path('bitacora/global/',        views.global_audit_log, name='global_audit_log'),
    path('<int:pk>/reasignar/', views.case_reassign, name='case_reassign'),
    path('<int:pk>/rechazar/', views.case_reject, name='case_reject'),
    path('reportes/por-estado/', views.case_report_by_state, name='case_report_by_state'),
    path('reportes/por-sala/', views.case_report_by_sala, name='case_report_by_sala'),
    path('exportar/excel/', views.export_cases_excel, name='export_cases_excel'),
    path('exportar/pdf/', views.export_cases_pdf, name='export_cases_pdf'),
    path('documentos/<int:document_id>/ver/', views.serve_case_document, name='serve_case_document'),
    path('<int:case_id>/interacciones/', views.case_add_interaction, name='case_add_interaction'),
    path('<int:case_id>/llamada/subir/', views.upload_call_recording, name='upload_call_recording'),
    path('metricas/comunicaciones/', views.communication_metrics, name='communication_metrics'),
    path('grabaciones/<int:interaction_id>/', views.serve_call_recording, name='serve_call_recording'),
    # WebRTC nativo
    path('<int:case_id>/webrtc/ice/', views.get_ice_servers, name='get_ice_servers'),
    path('<int:case_id>/webrtc/crear/', views.create_call_session, name='create_call_session'),
    path('<int:case_id>/webrtc/<str:room_id>/oferta/', views.set_call_offer, name='set_call_offer'),
    path('<int:case_id>/webrtc/<str:room_id>/respuesta/', views.set_call_answer, name='set_call_answer'),
    path('<int:case_id>/webrtc/<str:room_id>/estado/', views.get_call_state, name='get_call_state'),
    path('<int:case_id>/webrtc/<str:room_id>/oferta/leer/', views.get_call_offer, name='get_call_offer'),
    path('<int:case_id>/webrtc/<str:room_id>/sala/', views.join_webrtc_call, name='join_webrtc_call'),
    path('reportes/tiempos-atencion/',          views.case_attention_time_report,   name='case_attention_time_report'),
    path('reportes/tiempos-atencion/excel/',    views.export_attention_time_excel,  name='export_attention_time_excel'),
    path('reportes/tiempos-atencion/pdf/',      views.export_attention_time_pdf,    name='export_attention_time_pdf'),
]
